### ISSUE TITLE
We need a build system if we want to use modern JS

### ISSUE THREAD

**Issue by fabiankaegy** [amberchunn/acfk-meal-planning-block#2]
Currently, the Block doesn't load. I believe the problem is that we currently use JSX & modern JavaScript but don't have a build system setup. I would recommend we take a look at [Zacs Advanced Gutenberg](https://github.com/zgordon/advanced-gutenberg-course) course repo to take his build system. 

The other option would be to use ES5 syntax. I have one example of that up in this repo: [Callout Block](https://github.com/fabiankaegy/callout-block/blob/master/callout-block.js). 

I will leave that up to whatever you, @amberchunn,  feel more comfortable with.

**Comment by amberchunn** [comment]
I like the idea of using Modern JS and JSX, but for simplicity I'll rewrite to use ES5 for now.
